default:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 16
      account: PNIYPAX-HS00508
      user: kejgs
      database: analytics
      warehouse: transforming
      schema: dbt_ekarels
      password: G738DPBW7tvpA7V
      role: ACCOUNTADMIN
